-- Migration 042: add Lift-axis TRAP requirements to the 15 curated challenges.
-- Migration 020 replaced the catalogue with rubric-only configs, so every submission's
-- trap_coverage judge saw (none) and scored a flat 5/10. json_set keeps the existing
-- profile and rubric and only adds $.traps. Re-running is idempotent.
-- Generated once; traps are authored from each challenge's problem statement.

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "patch-validation", "description": "PATCH must validate the same way POST does: a status outside wishlist|reading|read, a non-integer year or an empty title returns a 4xx with a clear error body, never a 500 and never a silently stored bad value. PATCH is the path a one-shot usually forgets to validate."}, {"id": "patch-partial-semantics", "description": "PATCH must change only the fields present in the body; omitted fields keep their previous values instead of being overwritten with null or defaults, and PATCH on an unknown id returns 404."}, {"id": "combined-filters", "description": "status, genre and q filters must combine with AND semantics and q must be a case-insensitive substring match; an implementation that applies only the first query param, or matches q case-sensitively, is wrong."}]'))
WHERE slug = 'bookshelf-rest-api' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "persist-while-typing", "description": "Edits must be persisted while the user types (debounced, off the keystroke path), not only on screen unmount or app background; saving only on navigation loses the last edit on force-quit, and a synchronous write per keystroke blocks the UI."}, {"id": "edit-resets-sync-state", "description": "Sync status is per-note state: creating, editing or deleting a note after it was synced must mark it unsynced again, including deletes made while offline, instead of keeping a stale synced marker."}, {"id": "sync-race", "description": "Going offline, or editing a note, during the fake 1s sync must not mark those notes synced; only notes whose content was captured at sync start may be marked synced when the delay resolves."}]'))
WHERE slug = 'offline-first-notes-app' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "derive-dont-mutate", "description": "The visible list must be derived from the source data (filter then sort a copy); calling Array.prototype.sort in place on the source array corrupts the original order so Reset no longer restores the initial view."}, {"id": "numeric-price-sort", "description": "Price sort must compare numbers, not strings (\"100\" sorts before \"20\" as strings), and name sort must be case-insensitive (localeCompare), so A to Z does not put all uppercase names first."}, {"id": "reset-clears-controls", "description": "Reset filters must clear the search text, every category checkbox and the sort selection, and the controlled inputs must visibly reflect the reset; resetting internal state while the inputs still show old values fails."}]'))
WHERE slug = 'searchable-product-listing-ui' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "natural-key-upsert", "description": "Idempotency must hinge on a natural key such as (partner, order_id) with an upsert; per-run columns like run_id and ingested_at must not make a re-run insert fresh rows, and the rejects table must not accumulate duplicates on re-run either."}, {"id": "money-without-floats", "description": "Amount normalization must not use float math: float(\"42.50\") * 100 style conversion produces off-by-one-cent values; parse with Decimal or string splitting, and recognize day-5 integer minor units so 4250 is not multiplied by 100 again."}, {"id": "stream-not-load", "description": "Files must be processed as a stream in bounded batches (csv reader iteration or chunked reads with batched commits); pandas.read_csv of the whole file or list(reader) holds the entire file in memory and fails the 5GB design requirement."}]'))
WHERE slug = 'idempotent-etl-pipeline-with-schema-drift' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "stable-hash", "description": "Bucketing must use a deterministic hash (sha256/murmur of tenant:flag:subject) compared as bucket < percent; Python''s built-in hash() is salted per process, so assignments change on every restart and subjects flap."}, {"id": "tenant-scoped-uniqueness", "description": "Flags must be unique per (tenant, key), not per key; a global unique key lets tenant B''s upsert overwrite tenant A''s flag of the same name, and evaluate must never resolve a key that exists only in another tenant."}, {"id": "unkill-restores-prior", "description": "Kill must be a separate killed state (or store the pre-kill rollout) so unkill restores exactly the prior rollout; implementing kill by overwriting rollout to off loses it, and an upsert while killed must not silently unkill the flag."}]'))
WHERE slug = 'multi-tenant-feature-flag-service' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "nonce-and-aad", "description": "Every AEAD encryption (value under DEK, DEK under KEK, KEK under master key) must use a fresh random nonce stored alongside the ciphertext, and the ciphertext should be bound to (tenant, secret name) via associated data so a blob cannot be swapped between secrets or tenants."}, {"id": "kek-versioned-rotation", "description": "Each wrapped DEK must record which KEK version wrapped it, and rotation re-wraps DEKs (not the secret values) while keeping the old KEK usable until every DEK is re-wrapped; a crash halfway then leaves a mixed but fully readable vault."}, {"id": "token-tenant-binding", "description": "A token must be bound to its tenant and expiry as well as its scopes: a tenant A token with scope * must not read tenant B''s secrets, expired tokens are rejected, token comparison uses a constant-time compare, and every denial is audited without echoing the token or the value."}]'))
WHERE slug = 'secrets-vault-with-envelope-encryption' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "tenant-scoped-cache", "description": "The semantic cache must be partitioned by tenant and invalidated when that tenant''s documents change or are deleted; a global similarity cache lets tenant B cache-hit tenant A''s answer, and stale entries keep citing deleted docs."}, {"id": "atomic-budget-reservation", "description": "The budget check must reserve the estimated cost atomically before calling the LLM; a read-check-then-call flow lets concurrent requests all pass and overshoot the cap. Retry-After must be computed to the actual budget reset, not a constant."}, {"id": "upsert-replaces-chunks", "description": "Upserting a new version of a doc_id must remove or supersede the previous version''s chunks, and soft-delete must remove chunks from retrieval immediately; otherwise stale chunks keep being retrieved and cited."}]'))
WHERE slug = 'production-rag-service-with-eval-harness-cost-guardrails' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "idempotency-in-transaction", "description": "The idempotency record must be claimed by a unique constraint inside the same transaction that writes the journal entries; a check-then-insert lookup lets two concurrent requests with the same key both create a transfer. Payload comparison should use a canonical hash of the request body."}, {"id": "balance-check-serialized", "description": "The overdraft check and the journal insert must run in one serialized transaction (BEGIN IMMEDIATE or SELECT ... FOR UPDATE on the source account); reading the balance and inserting in separate steps lets a flurry of transfers push a non-credit-line account negative. The limit is balance >= -credit_line_minor."}, {"id": "reversal-guards", "description": "A transfer can be reversed only once, the reversal must pass the same balance check on the original destination account, and amount_minor must be a positive integer with source != destination; zero, negative, float or self transfers are rejected."}]'))
WHERE slug = 'multi-currency-wallet-ledger-with-idempotent-transfers' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "backfill-respects-dual-write", "description": "The backfill must only fill rows whose shipping_address_id is still NULL and must page by primary key from a checkpoint, not OFFSET; overwriting rows the dual-write path already set, or re-scanning with OFFSET, causes divergence or quadratic slowdown on 50M rows."}, {"id": "expand-phase-compatible", "description": "The expand phase must be backward compatible with the previous code: the new column is nullable with no table-rewriting default, indexes are built non-blocking, and NOT NULL or FK constraints are added only after the backfill is verified. Dropping the old column must wait until no replica''s code (including SELECT * or ORM models) references it."}, {"id": "drain-ordering", "description": "On SIGTERM the instance must first fail /readyz so the load balancer stops routing, then drain in-flight requests, then exit, while /livez stays healthy during the drain; flipping liveness or exiting immediately drops requests mid-cutover."}]'))
WHERE slug = 'zero-downtime-schema-migration-progressive-rollout' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "commit-current-term-only", "description": "A leader must only advance commitIndex by counting replicas for an entry from its own current term (Raft Figure 8); committing an older-term entry because it reached a majority can later be overwritten, violating safety."}, {"id": "persist-before-reply", "description": "currentTerm, votedFor and appended log entries must be persisted before replying to RequestVote or AppendEntries; granting a vote and crashing before persisting lets the restarted node vote twice in the same term."}, {"id": "truncate-only-on-conflict", "description": "A follower must truncate its log only from the first index whose term conflicts, not unconditionally after prevLogIndex; a delayed or duplicated stale AppendEntries would otherwise delete already-appended (possibly committed) entries. commitIndex becomes min(leaderCommit, index of last new entry)."}]'))
WHERE slug = 'raft-lite-log-replication' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "out-of-order-ops", "description": "An op can arrive before the op it depends on (a delete or insert referencing an id not yet seen); it must be buffered until its dependency arrives, or causal delivery must be explicitly enforced, never dropped or allowed to crash."}, {"id": "visible-index-mapping", "description": "insert(index) and delete(index, length) must map visible positions by skipping tombstones; counting tombstones in position math places inserts and deletes in the wrong spot after any prior deletion."}, {"id": "per-char-ids-and-clock", "description": "insert(index, \"abc\") must give every character its own id (or a run with addressable per-offset ids) so a concurrent insert or delete inside the run works, and the Lamport counter must advance to max(seen)+1 on apply so later local inserts order correctly against remote siblings."}]'))
WHERE slug = 'crdt-collaborative-text-buffer' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "late-point-updates-parents", "description": "A late point within retention must update its raw bucket and every coarser rollup containing it; last must be chosen by timestamp, not arrival order, so a late point never overwrites a newer last value."}, {"id": "avg-from-sum-count", "description": "Averages over a range must be computed as total sum / total count across buckets, never as the average of bucket averages, which is wrong whenever buckets hold different point counts."}, {"id": "aligned-steps-explicit-gaps", "description": "Query buckets must align to epoch step boundaries (floor(ts / step) * step), the chosen rollup level must still cover the requested range under its retention, and empty buckets must be returned as explicit gaps rather than zero values."}]'))
WHERE slug = 'time-series-metrics-store' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "update-removes-old-postings", "description": "update and delete must remove postings for terms in the old text and adjust df, N and total length (avgdl); df must count documents, not term occurrences, or ghost postings and stale stats skew every score."}, {"id": "same-analysis-for-queries", "description": "Query terms, including typo candidates, must pass through the same tokenizer, case folding and stemming as indexed text; otherwise \"Running\" never matches an index that stored \"run\", and exact matches should outrank fuzzy ones."}, {"id": "bm25-idf-and-ties", "description": "BM25 idf must use the non-negative form log(1 + (N - df + 0.5) / (df + 0.5)) (or clamp) so very common terms don''t produce negative scores, and ties must break deterministically, for example by doc_id."}]'))
WHERE slug = 'inverted-index-search-with-ranking' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "denied-not-recorded", "description": "Denied requests must not be appended to the sliding log or counted against the quota; recording before deciding makes a client that keeps retrying lock itself out indefinitely."}, {"id": "atomic-rate-and-quota", "description": "The rate check, quota check and both increments must happen in one atomic step per key; incrementing the rate counter before discovering the quota is exhausted (or the reverse) consumes budget on a denied request."}, {"id": "eviction-preserves-quota", "description": "Cold-key eviction must only remove state idle longer than the longest window (the daily quota), not the 60s rate window; evicting after a short idle period silently resets a tenant''s daily quota."}]'))
WHERE slug = 'multi-tenant-rate-limiter-quota-service' AND json_valid(scoring_config);

UPDATE challenges SET scoring_config = json_set(scoring_config, '$.traps', json('[{"id": "attempts-and-cap", "description": "Total attempts must be exactly retries + 1, the delay must follow the documented base * 2^attempt formula with the cap applied after jitter so the delay never exceeds the maximum."}, {"id": "transitive-skip-terminates", "description": "A permanent failure must skip all transitive descendants, not only direct children, and the run must terminate with them marked skipped; leaving never-ready tasks pending deadlocks the scheduler."}, {"id": "backoff-releases-slot", "description": "A task waiting out its backoff must not hold a concurrency slot, and due retries must re-enter the same capped queue as fresh tasks, so the global limit holds across retries and fan-out."}]'))
WHERE slug = 'process-task-orchestrator-lite' AND json_valid(scoring_config);
