"""Generator script for migration 020: 6 new senior challenges from CHALLENGE_LIBRARY,
plus deletion of all legacy seed challenges outside the curated 15-slug catalog.

Run from the repo root:
    python scripts/gen_library_migration.py

Emits:
    migrations/020_curate_quality_catalog.sql
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

# Ensure the repo root is on sys.path so `app` is importable.
REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT))

from app.services.challenge_library import CHALLENGE_LIBRARY  # noqa: E402

# ---------------------------------------------------------------------------
# Helpers (mirror gen_quality_challenges_migration.py)
# ---------------------------------------------------------------------------


def sql_escape(text: str) -> str:
    """Escape a string for use as a SQL single-quoted literal."""
    return text.replace("'", "''")


def sq(text: str) -> str:
    """Wrap in single quotes after escaping."""
    return "'" + sql_escape(text) + "'"


# ---------------------------------------------------------------------------
# Keep-list: 9 quality slugs from migration 019 + 6 new library slugs
# ---------------------------------------------------------------------------

QUALITY_SLUGS_019: list[str] = [
    "searchable-product-listing-ui",
    "offline-first-notes-app",
    "bookshelf-rest-api",
    "idempotent-etl-pipeline-with-schema-drift",
    "multi-tenant-feature-flag-service",
    "secrets-vault-with-envelope-encryption",
    "production-rag-service-with-eval-harness-cost-guardrails",
    "multi-currency-wallet-ledger-with-idempotent-transfers",
    "zero-downtime-schema-migration-progressive-rollout",
]

# Tags for the 6 library challenges (keyed by slug)
TAGS: dict[str, list[str]] = {
    "raft-lite-log-replication":              ["distributed-systems", "consensus", "raft", "simulation"],
    "crdt-collaborative-text-buffer":         ["crdt", "collaboration", "realtime", "distributed"],
    "time-series-metrics-store":              ["time-series", "metrics", "observability", "data"],
    "inverted-index-search-with-ranking":     ["search", "information-retrieval", "ranking", "bm25"],
    "multi-tenant-rate-limiter-quota-service": ["rate-limiting", "multi-tenant", "platform", "concurrency"],
    "process-task-orchestrator-lite":         ["orchestration", "dag", "scheduling", "backoff"],
}

# Problem-statement markdown per slug — verbatim from CHALLENGE_LIBRARY source file.
# We generate these at runtime from the imported CHALLENGE_LIBRARY entries.
# Each entry's problem statement is the full markdown in the *_PROBLEM constants;
# they are passed as `description` in the library dict (the large block).
# We store the multi-line text blocks directly via the _PROBLEM constants.
# Because the generator imports the library at runtime, we reference the source
# variable names for clarity but they are just strings.

# Map slug → problem statement text (from the library source constants).
# We can derive these by pulling the `description` field from CHALLENGE_LIBRARY —
# but the description in CHALLENGE_LIBRARY is a short one-liner description,
# not the full markdown. The full markdown lives in the *_PROBLEM module-level
# constants. Import them directly.
from app.services.challenge_library import (  # noqa: E402
    RAFT_PROBLEM,
    CRDT_PROBLEM,
    TSDB_PROBLEM,
    SEARCH_PROBLEM,
    RATELIMIT_PROBLEM,
    ORCHESTRATOR_PROBLEM,
)

PROBLEM_STATEMENTS: dict[str, str] = {
    "raft-lite-log-replication":              RAFT_PROBLEM,
    "crdt-collaborative-text-buffer":         CRDT_PROBLEM,
    "time-series-metrics-store":              TSDB_PROBLEM,
    "inverted-index-search-with-ranking":     SEARCH_PROBLEM,
    "multi-tenant-rate-limiter-quota-service": RATELIMIT_PROBLEM,
    "process-task-orchestrator-lite":         ORCHESTRATOR_PROBLEM,
}


def generate_migration() -> str:
    lines: list[str] = []

    # Derive the 6 new slugs from CHALLENGE_LIBRARY
    new_slugs: list[str] = [ch["slug"] for ch in CHALLENGE_LIBRARY]

    # Full 15-slug keep-list
    keep_slugs: list[str] = QUALITY_SLUGS_019 + new_slugs

    assert len(keep_slugs) == 15, f"Expected 15 keep slugs, got {len(keep_slugs)}"

    lines.append("-- Migration 020: curate quality catalog to exactly 15 challenges")
    lines.append("-- Generated by scripts/gen_library_migration.py")
    lines.append("--")
    lines.append("-- Part 1: INSERT OR IGNORE the 6 new HARD senior challenges from CHALLENGE_LIBRARY.")
    lines.append("-- Part 2: DELETE every challenge (and its FK dependents) NOT in the 15-slug keep-list.")
    lines.append("--")
    lines.append("-- created_by = 'system' (mirrors migrations 003-019)")
    lines.append("-- scoring_config = {\"profile\":\"spec_heavy\",\"rubric\":<verbatim>}")
    lines.append("-- PRAGMA foreign_keys = OFF wraps the whole file (mirrors 019 pattern).")
    lines.append("")
    lines.append("PRAGMA foreign_keys = OFF;")
    lines.append("")

    # ------------------------------------------------------------------
    # Part 1: INSERT the 6 new library challenges
    # ------------------------------------------------------------------
    lines.append("-- ============================================================")
    lines.append("-- Part 1: Insert 6 new senior challenges from CHALLENGE_LIBRARY")
    lines.append("-- ============================================================")
    lines.append("")

    for i, challenge in enumerate(CHALLENGE_LIBRARY, start=1):
        slug = challenge["slug"]
        title = challenge["title"]
        description = challenge["description"]
        problem_statement_md = PROBLEM_STATEMENTS[slug]
        difficulty = challenge["difficulty"]
        category = challenge["category"]
        time_limit_minutes = challenge["time_limit_minutes"]
        max_budget_usd = challenge["max_budget_usd"]
        rubric = challenge["rubric"]

        tags_list = TAGS.get(slug, [])
        tags_json = json.dumps(tags_list)

        scoring_config = json.dumps({"profile": "spec_heavy", "rubric": rubric})

        challenge_id = f"library_challenge_{i:03d}"

        lines.append(f"-- ------------------------------------------------------------")
        lines.append(f"-- L{i}: {title}")
        lines.append(f"-- slug: {slug} | category: {category} | difficulty: {difficulty}")
        lines.append(f"-- rubric dimensions: {len(rubric)}")
        lines.append(f"-- ------------------------------------------------------------")
        lines.append("")
        lines.append("INSERT OR IGNORE INTO challenges")
        lines.append("    (id, created_by, title, slug, description, problem_statement_md,")
        lines.append("     difficulty, category, tags, time_limit_minutes, test_suite,")
        lines.append("     scoring_config, starter_files, max_budget_usd, is_public, is_featured)")
        lines.append("VALUES")
        lines.append("(")
        lines.append(f"    {sq(challenge_id)},")
        lines.append(f"    'system',")
        lines.append(f"    {sq(title)},")
        lines.append(f"    {sq(slug)},")
        lines.append(f"    {sq(description)},")
        lines.append(f"    {sq(problem_statement_md)},")
        lines.append(f"    '{difficulty}',")
        lines.append(f"    '{category}',")
        lines.append(f"    {sq(tags_json)},")
        lines.append(f"    {time_limit_minutes},")
        lines.append(f"    NULL,")
        lines.append(f"    {sq(scoring_config)},")
        lines.append(f"    NULL,")
        lines.append(f"    {max_budget_usd},")
        lines.append(f"    1,")
        lines.append(f"    1")
        lines.append(");")
        lines.append("")

    # ------------------------------------------------------------------
    # Part 2: DELETE challenges not in the 15-slug keep-list
    # ------------------------------------------------------------------
    slug_list_sql = ", ".join(sq(s) for s in keep_slugs)

    lines.append("-- ============================================================")
    lines.append("-- Part 2: Delete legacy/junk challenges outside the keep-list.")
    lines.append("-- FK dependents are cleaned first; then the challenges row.")
    lines.append("-- PRAGMA foreign_keys = OFF is already set above.")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append(f"-- Keep-list ({len(keep_slugs)} slugs):")
    for s in keep_slugs:
        lines.append(f"--   {s}")
    lines.append("")

    # Delete FK dependents for doomed challenges
    lines.append("-- Delete FK dependents for doomed challenges")
    lines.append("DELETE FROM submissions")
    lines.append(f"    WHERE challenge_id IN (SELECT id FROM challenges WHERE slug NOT IN ({slug_list_sql}));")
    lines.append("")
    lines.append("DELETE FROM leaderboard_entries")
    lines.append(f"    WHERE challenge_id IN (SELECT id FROM challenges WHERE slug NOT IN ({slug_list_sql}));")
    lines.append("")
    lines.append("DELETE FROM challenge_feedback")
    lines.append(f"    WHERE challenge_id IN (SELECT id FROM challenges WHERE slug NOT IN ({slug_list_sql}));")
    lines.append("")
    lines.append("-- Delete the doomed challenges themselves")
    lines.append(f"DELETE FROM challenges WHERE slug NOT IN ({slug_list_sql});")
    lines.append("")
    lines.append("PRAGMA foreign_keys = ON;")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    sql = generate_migration()

    out_path = REPO_ROOT / "migrations" / "020_curate_quality_catalog.sql"
    out_path.write_text(sql, encoding="utf-8")
    print(f"Written: {out_path}")

    # Print summary
    new_slugs = [ch["slug"] for ch in CHALLENGE_LIBRARY]
    keep_slugs = QUALITY_SLUGS_019 + new_slugs

    print(f"\n6 new challenges inserted:")
    for i, ch in enumerate(CHALLENGE_LIBRARY, start=1):
        print(f"  L{i}: {ch['slug']}  [{ch['category']}]  {len(ch['rubric'])} dims")

    print(f"\n15-slug keep-list:")
    for s in keep_slugs:
        print(f"  {s}")

    print(f"\nAll other challenges will be DELETED.")


if __name__ == "__main__":
    main()
